### ISSUE TITLE
유효하지 않은 맵 파일을 인자로 받을 때마다 발생하는 Abort() 에러 

### ISSUE THREAD

**Issue by objectio** [S0YKIM/Cub3d#28]
- 프로그램의 인자로 유효하지 않은 맵 파일을 넣었을 때 double free로 인한 Abort()에러가 발생
- 유효하지 않은 맵 테스트 : 맵 컨텐츠 사이에 개행이 있거나, 테두리가 1로 감싸져 있지 않은 경우

**Comment by S0YKIM** [comment]
<img width="1117" alt="Screen Shot 2022-09-01 at 11 05 18 AM" src="https://user-images.githubusercontent.com/72473178/187817029-3095b8af-c5e6-4430-a131-373e8abd017b.png">
