### ISSUE TITLE
Wall rendering error

### ISSUE THREAD

**Issue by objectio** [S0YKIM/Cub3d#49]
- [x] 이동할 때 그려지는 프레임이 부드럽게 연결되지 않고 간헐적으로 프레임이 튀는 현상 발생
- [x] player를 움직이면 움직일 수록 벽의 높이가 왜곡되는 현상
- [x] 벽이 그려지지 않은 곳으로 player를 이동시키면 벽에 막혀 나아가지 않음
- [x] 실제 맵과 화면 상에 렌더링되고 있는 벽 사이에 괴리가 있음

**Comment by S0YKIM** [comment]
#53 #52 #51
